#!/bin/bash
for lib in `qemu-arm -E LD_TRACE_LOADED_OBJECTS=1 $1 | awk 'BEGIN{ORS=" "}$1~/^\//{print $1}$3~/^\//{print $3}' | sed 's/,$/\n/'`
do 
    bl=`basename $lib`
    if [ "$bl" == "ld-linux-armhf.so.3" ] || \
       [ "$bl" == "libpthread.so.0" ] || \
       [ "$bl" == "libc.so.6" ] || \
       [ "$bl" == "libstdc++.so.6" ] || \
       [ "$bl" == "libdl.so.2" ] || \
       [ "$bl" == "libgcc_s.so.1" ]; then
        echo "lib $bl ignored"
    else
        cp $lib $2
    fi
done